{
 "title": "Llama Swap",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Total Requests (Last minute)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model) (increase(llama_swap_requests_total{model=\"\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prompt Processing Speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Tokens / sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "llama_swap_prompt_tokens_per_second_last_1{model=\"\"}",
     "legendFormat": "Last 1"
    },
    {
     "expr": "llama_swap_prompt_tokens_per_second_last_5{model=\"\"}",
     "legendFormat": "Last 5"
    },
    {
     "expr": "llama_swap_prompt_tokens_per_second_last_15{model=\"\"}",
     "legendFormat": "Last 15"
    }
   ]
  },
  {
   "title": "Generation Speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Tokens / sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "llama_swap_generate_tokens_per_second_last_1{model=\"\"}",
     "legendFormat": "Last 1"
    },
    {
     "expr": "llama_swap_generate_tokens_per_second_last_5{model=\"\"}",
     "legendFormat": "Last 5"
    },
    {
     "expr": "llama_swap_generate_tokens_per_second_last_15{model=\"\"}",
     "legendFormat": "Last 15"
    }
   ]
  },
  {
   "title": "Input Tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Tokens" } },
   "targets": [
    {
     "expr": "sum by (model) (increase(llama_swap_input_tokens_total{model=~\".+\"}[1m]))",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Output Tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Tokens" } },
   "targets": [
    {
     "expr": "sum by (model) (increase(llama_swap_output_tokens_total{model=~\".+\"}[1m]))",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Cached Tokens",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Tokens" } },
   "targets": [
    {
     "expr": "sum by (model) (increase(llama_swap_cached_tokens_total{model=~\".+\"}[1m]))",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Cache Efficiency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$B / $A", "type": "math" }
   ]
  }
 ]
}