{{- if not .Values.config.existing }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "llama-swap.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "llama-swap.labels" . | nindent 4 }}
data:
  config.yaml: |
{{- with .Values.config.inline }}
{{- tpl . $ | nindent 4 }}
{{- end }}
{{- range $name, $content := .Values.config.extraFiles }}
  {{ $name }}: |
{{- tpl $content $ | nindent 4 }}
{{- end }}
{{- end }}
