#!/usr/bin/env bash
set -euo pipefail

IFACE="${IFACE:-}"
MODE="${MODE:-perf}"     # perf | debug
APPLY=0
SHOW=0
ROLLBACK_FILE=""
SNAPSHOT_FILE="${SNAPSHOT_FILE:-}"

SYSCTL_KEYS=(
  net.ipv4.tcp_keepalive_time
  net.ipv4.tcp_keepalive_intvl
  net.ipv4.tcp_keepalive_probes
  net.ipv4.tcp_retries2
  net.core.rmem_max
  net.core.wmem_max
  net.core.netdev_max_backlog
)

usage() {
  cat <<'EOF'
Usage:
  net-tune-canary.sh --apply [--iface IFACE] [--mode perf|debug] [--snapshot-file FILE]
  net-tune-canary.sh --rollback FILE
  net-tune-canary.sh --show

Behavior:
  --apply     Applies canary sysctl values and offload mode for IFACE.
  --rollback  Restores sysctl values from snapshot generated by --apply.
  --show      Prints current relevant sysctl values and offload state.

Modes:
  perf  : tso/gso/gro on  (recommended)
  debug : tso/gso/gro/lro off (temporary troubleshooting)

Environment fallback:
  IFACE, MODE, SNAPSHOT_FILE
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --iface) IFACE="$2"; shift 2 ;;
    --mode) MODE="$2"; shift 2 ;;
    --apply) APPLY=1; shift ;;
    --show) SHOW=1; shift ;;
    --rollback) ROLLBACK_FILE="$2"; shift 2 ;;
    --snapshot-file) SNAPSHOT_FILE="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage; exit 1 ;;
  esac
done

if [[ "$SHOW" -eq 1 ]]; then
  for key in "${SYSCTL_KEYS[@]}"; do
    sysctl -n "$key" 2>/dev/null | awk -v k="$key" '{print k "=" $0}'
  done
  if [[ -n "$IFACE" ]] && command -v ethtool >/dev/null 2>&1; then
    ethtool -k "$IFACE" | grep -E 'tcp-segmentation-offload|generic-segmentation-offload|generic-receive-offload|large-receive-offload' || true
  fi
  exit 0
fi

if [[ -n "$ROLLBACK_FILE" ]]; then
  if [[ ! -f "$ROLLBACK_FILE" ]]; then
    echo "Rollback file not found: $ROLLBACK_FILE" >&2
    exit 1
  fi
  while IFS='=' read -r key value; do
    [[ -z "$key" ]] && continue
    sysctl -w "${key}=${value}" >/dev/null
  done < "$ROLLBACK_FILE"
  echo "Rollback applied from: $ROLLBACK_FILE"
  exit 0
fi

if [[ "$APPLY" -ne 1 ]]; then
  usage
  exit 1
fi

if [[ "$EUID" -ne 0 ]]; then
  echo "Run as root for sysctl/ethtool changes." >&2
  exit 1
fi

if [[ -z "$SNAPSHOT_FILE" ]]; then
  SNAPSHOT_FILE="/root/sysctl.canary.pre.$(date +%F_%H%M%S)"
fi

{
  for key in "${SYSCTL_KEYS[@]}"; do
    printf '%s=%s\n' "$key" "$(sysctl -n "$key" 2>/dev/null || true)"
  done
} > "$SNAPSHOT_FILE"
echo "Snapshot saved: $SNAPSHOT_FILE"

sysctl -w \
  net.ipv4.tcp_keepalive_time=120 \
  net.ipv4.tcp_keepalive_intvl=20 \
  net.ipv4.tcp_keepalive_probes=6 \
  net.ipv4.tcp_retries2=8 \
  net.core.rmem_max=16777216 \
  net.core.wmem_max=16777216 \
  net.core.netdev_max_backlog=250000 >/dev/null

if [[ -n "$IFACE" ]] && command -v ethtool >/dev/null 2>&1; then
  if [[ "$MODE" == "debug" ]]; then
    ethtool -K "$IFACE" tso off gso off gro off lro off || true
  else
    ethtool -K "$IFACE" tso on gso on gro on || true
  fi
fi

echo "Canary network tuning applied. mode=$MODE iface=${IFACE:-none}"
