name: UI Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - 'ui-svelte/**'
      - '.github/workflows/ui-tests.yml'

  pull_request:
    branches: [ "main" ]
    paths:
      - 'ui-svelte/**'
      - '.github/workflows/ui-tests.yml'

  workflow_dispatch:

jobs:

  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2

    - name: Set up Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # 6.4.0
      with:
        node-version: '24'
        cache: 'npm'
        cache-dependency-path: ui-svelte/package-lock.json

    - name: Run UI tests
      run: make test-ui
